name: Terraform Checks

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  terraform-check:
    name: Terraform Check.
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      # Run terraform fmt
      - name: Terraform fmt
        run: terraform fmt -check -recursive

      # Run terraform validate
      - name: Terraform validate
        run: terraform validate
